INSERT INTO apolices ([apo_cod], [apo_im_cod], [apo_cli_cod], [apo_dt_cad], [apo_dt_alt], [apo_dt_inicio_vigencia], [apo_dt_fim_vigencia], [apo_valor_cobertura], [apo_valor_franquia])
VALUES
    (1, 1, 1, '2023-01-01', '2023-01-05', '2023-02-01', '2024-01-31', 500000, 10000),
    (2, 2, 1, '2023-01-02', '2023-01-06', '2023-03-01', '2024-02-29', 400000, 8000),
    (3, 3, 1, '2023-01-03', '2023-01-07', '2023-04-01', '2024-03-31', 600000, 12000),
    (4, 4, 4, '2023-01-04', '2023-01-08', '2023-05-01', '2024-04-30', 550000, 11000),
    (5, 5, 5, '2023-01-05', '2023-01-09', '2023-06-01', '2024-05-31', 480000, 9600),
    (6, 6, 6, '2023-01-06', '2023-01-10', '2023-07-01', '2024-06-30', 520000, 10400),
    (7, 7, 7, '2023-01-07', '2023-01-11', '2023-08-01', '2024-07-31', 650000, 13000),
    (8, 8, 8, '2023-01-08', '2023-01-12', '2023-09-01', '2024-08-31', 470000, 9400),
    (9, 9, 8, '2023-01-09', '2023-01-13', '2023-10-01', '2024-09-30', 510000, 10200),
    (10, 10, 10, '2023-01-10', '2023-01-14', '2023-11-01', '2024-10-31', 590000, 11800),
    (11, 11, 11, '2023-01-11', '2023-01-15', '2023-12-01', '2024-11-30', 630000, 12600);


INSERT INTO apolice_itens ([api_cod], [api_apo_cod], [api_descricao])
VALUES
    (1, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas non tellus id tortor eleifend dictum. Morbi id mollis justo, eu sodales ante. Sed ac aliquet enim. Donec tincidunt metus ac nisl vestibulum, vitae fringilla nulla congue. Curabitur viverra urna eu arcu auctor, sit amet lobortis sapien finibus. Suspendisse potenti. Praesent ullamcorper vulputate orci vitae scelerisque. Sed at nulla nec velit eleifend commodo. Nam dapibus velit a leo placerat, nec commodo mi tristique. Duis non odio nec libero eleifend sagittis. Nullam ut odio turpis. In a massa sed turpis auctor posuere. Sed sit amet odio nec ex sollicitudin tristique. Fusce aliquet venenatis justo, sit amet ultricies magna scelerisque eget.'),
    (2, 2, 'Suspendisse vitae quam varius, sollicitudin sapien in, gravida urna. Duis ultricies turpis justo, ac posuere libero facilisis eu. Aenean id metus vel neque convallis tincidunt a nec sapien. Integer hendrerit ultrices fermentum. Phasellus eget aliquam lorem, id dictum nulla. Donec tristique aliquet turpis a feugiat. Etiam id ipsum a augue tempor facilisis in sit amet nisi. Suspendisse potenti. Nullam commodo varius justo, eu lacinia lectus tempor at. Vestibulum euismod commodo lacus, a interdum lectus euismod at. Maecenas auctor euismod eros non vehicula. Nullam sed arcu quis libero maximus malesuada. Sed eu quam vitae lectus aliquam convallis. Aliquam consequat, nisi in laoreet commodo, quam leo facilisis libero, et placerat ante orci et mi.'),
    (3, 3, 'Vivamus placerat commodo eros, id congue neque dictum eget. Sed nec nunc libero. Nam nec odio nec nisl blandit lacinia a eget est. Nulla varius hendrerit metus, eget sodales nulla ullamcorper in. Nam feugiat tellus sed turpis tempor, in ultricies lacus facilisis. Curabitur vestibulum placerat nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed sit amet leo nec quam consequat faucibus eu nec est. Nulla facilisi. Cras nec convallis elit. Vivamus quis mi justo. Sed nec posuere urna, nec auctor purus. Curabitur finibus justo sit amet justo facilisis, id auctor urna efficitur.'),
    (4, 4, 'Pellentesque eget mauris quis augue feugiat tincidunt. Vivamus pharetra, metus sit amet gravida posuere, magna mi rhoncus ligula, vitae fermentum elit enim id sapien. Fusce tristique volutpat sapien, id laoreet ipsum consequat ut. Donec hendrerit, lacus in efficitur eleifend, turpis odio hendrerit neque, a eleifend elit urna nec velit. In hac habitasse platea dictumst. Aliquam sagittis lectus et libero tincidunt, at laoreet risus dictum. Morbi id augue in lectus vulputate vulputate at id diam. Ut eget odio vehicula, aliquam ante eget, dictum neque. Nulla facilisi. Aenean eget erat sed est placerat sodales. Suspendisse potenti. Nam id risus ultricies, vulputate lectus nec, suscipit urna. Sed non velit vestibulum, consequat libero ut, consectetur justo.'),
    (5, 5, 'Proin vitae maximus purus. Sed ut turpis sit amet tortor congue placerat. Integer convallis magna nec ipsum consectetur facilisis. Duis mollis bibendum erat, vitae scelerisque ipsum feugiat vel. Vestibulum malesuada posuere sem, in egestas tortor laoreet nec. Nulla facilisi. Proin sodales justo a libero tincidunt, non eleifend magna dictum. Maecenas tincidunt nibh sit amet rhoncus tincidunt. Sed nec sem in ligula placerat consectetur id eu ligula. Aliquam erat volutpat. Etiam ac lacinia arcu, in tincidunt elit. Donec elementum magna a fermentum fringilla. Suspendisse lacinia purus a nibh luctus bibendum. Nullam vitae tristique metus. Donec tincidunt id ante sit amet tincidunt. Aliquam nec malesuada orci, vel ultrices magna. Donec ultricies, enim at scelerisque eleifend, elit enim luctus ligula, vitae laoreet lacus lorem eget odio.'),
    (6, 10, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas non tellus id tortor eleifend dictum. Morbi id mollis justo, eu sodales ante. Sed ac aliquet enim. Donec tincidunt metus ac nisl vestibulum, vitae fringilla nulla congue. Curabitur viverra urna eu arcu auctor, sit amet lobortis sapien finibus. Suspendisse potenti. Praesent ullamcorper vulputate orci vitae scelerisque. Sed at nulla nec velit eleifend commodo. Nam dapibus velit a leo placerat, nec commodo mi tristique. Duis non odio nec libero eleifend sagittis. Nullam ut odio turpis. In a massa sed turpis auctor posuere. Sed sit amet odio nec ex sollicitudin tristique. Fusce aliquet venenatis justo, sit amet ultricies magna scelerisque eget.'),
    (7, 11, 'Suspendisse vitae quam varius, sollicitudin sapien in, gravida urna. Duis ultricies turpis justo, ac posuere libero facilisis eu. Aenean id metus vel neque convallis tincidunt a nec sapien. Integer hendrerit ultrices fermentum. Phasellus eget aliquam lorem, id dictum nulla. Donec tristique aliquet turpis a feugiat. Etiam id ipsum a augue tempor facilisis in sit amet nisi. Suspendisse potenti. Nullam commodo varius justo, eu lacinia lectus tempor at. Vestibulum euismod commodo lacus, a interdum lectus euismod at. Maecenas auctor euismod eros non vehicula. Nullam sed arcu quis libero maximus malesuada. Sed eu quam vitae lectus aliquam convallis. Aliquam consequat, nisi in laoreet commodo, quam leo facilisis libero, et placerat ante orci et mi.'),
    (8, 10, 'Vivamus placerat commodo eros, id congue neque dictum eget. Sed nec nunc libero. Nam nec odio nec nisl blandit lacinia a eget est. Nulla varius hendrerit metus, eget sodales nulla ullamcorper in. Nam feugiat tellus sed turpis tempor, in ultricies lacus facilisis. Curabitur vestibulum placerat nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed sit amet leo nec quam consequat faucibus eu nec est. Nulla facilisi. Cras nec convallis elit. Vivamus quis mi justo. Sed nec posuere urna, nec auctor purus. Curabitur finibus justo sit amet justo facilisis, id auctor urna efficitur.'),
    (9, 4, 'Pellentesque eget mauris quis augue feugiat tincidunt. Vivamus pharetra, metus sit amet gravida posuere, magna mi rhoncus ligula, vitae fermentum elit enim id sapien. Fusce tristique volutpat sapien, id laoreet ipsum consequat ut. Donec hendrerit, lacus in efficitur eleifend, turpis odio hendrerit neque, a eleifend elit urna nec velit. In hac habitasse platea dictumst. Aliquam sagittis lectus et libero tincidunt, at laoreet risus dictum. Morbi id augue in lectus vulputate vulputate at id diam. Ut eget odio vehicula, aliquam ante eget, dictum neque. Nulla facilisi. Aenean eget erat sed est placerat sodales. Suspendisse potenti. Nam id risus ultricies, vulputate lectus nec, suscipit urna. Sed non velit vestibulum, consequat libero ut, consectetur justo.'),
    (10, 5, 'Proin vitae maximus purus. Sed ut turpis sit amet tortor congue placerat. Integer convallis magna nec ipsum consectetur facilisis. Duis mollis bibendum erat, vitae scelerisque ipsum feugiat vel. Vestibulum malesuada posuere sem, in egestas tortor laoreet nec. Nulla facilisi. Proin sodales justo a libero tincidunt, non eleifend magna dictum. Maecenas tincidunt nibh sit amet rhoncus tincidunt. Sed nec sem in ligula placerat consectetur id eu ligula. Aliquam erat volutpat. Etiam ac lacinia arcu, in tincidunt elit. Donec elementum magna a fermentum fringilla. Suspendisse lacinia purus a nibh luctus bibendum. Nullam vitae tristique metus. Donec tincidunt id ante sit amet tincidunt. Aliquam nec malesuada orci, vel ultrices magna. Donec ultricies, enim at scelerisque eleifend, elit enim luctus ligula, vitae laoreet lacus lorem eget odio.'),
    (11, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas non tellus id tortor eleifend dictum. Morbi id mollis justo, eu sodales ante. Sed ac aliquet enim. Donec tincidunt metus ac nisl vestibulum, vitae fringilla nulla congue. Curabitur viverra urna eu arcu auctor, sit amet lobortis sapien finibus. Suspendisse potenti. Praesent ullamcorper vulputate orci vitae scelerisque. Sed at nulla nec velit eleifend commodo. Nam dapibus velit a leo placerat, nec commodo mi tristique. Duis non odio nec libero eleifend sagittis. Nullam ut odio turpis. In a massa sed turpis auctor posuere. Sed sit amet odio nec ex sollicitudin tristique. Fusce aliquet venenatis justo, sit amet ultricies magna scelerisque eget.'),
    (12, 2, 'Suspendisse vitae quam varius, sollicitudin sapien in, gravida urna. Duis ultricies turpis justo, ac posuere libero facilisis eu. Aenean id metus vel neque convallis tincidunt a nec sapien. Integer hendrerit ultrices fermentum. Phasellus eget aliquam lorem, id dictum nulla. Donec tristique aliquet turpis a feugiat. Etiam id ipsum a augue tempor facilisis in sit amet nisi. Suspendisse potenti. Nullam commodo varius justo, eu lacinia lectus tempor at. Vestibulum euismod commodo lacus, a interdum lectus euismod at. Maecenas auctor euismod eros non vehicula. Nullam sed arcu quis libero maximus malesuada. Sed eu quam vitae lectus aliquam convallis. Aliquam consequat, nisi in laoreet commodo, quam leo facilisis libero, et placerat ante orci et mi.'),
    (13, 3, 'Vivamus placerat commodo eros, id congue neque dictum eget. Sed nec nunc libero. Nam nec odio nec nisl blandit lacinia a eget est. Nulla varius hendrerit metus, eget sodales nulla ullamcorper in. Nam feugiat tellus sed turpis tempor, in ultricies lacus facilisis. Curabitur vestibulum placerat nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed sit amet leo nec quam consequat faucibus eu nec est. Nulla facilisi. Cras nec convallis elit. Vivamus quis mi justo. Sed nec posuere urna, nec auctor purus. Curabitur finibus justo sit amet justo facilisis, id auctor urna efficitur.'),
    (14, 4, 'Pellentesque eget mauris quis augue feugiat tincidunt. Vivamus pharetra, metus sit amet gravida posuere, magna mi rhoncus ligula, vitae fermentum elit enim id sapien. Fusce tristique volutpat sapien, id laoreet ipsum consequat ut. Donec hendrerit, lacus in efficitur eleifend, turpis odio hendrerit neque, a eleifend elit urna nec velit. In hac habitasse platea dictumst. Aliquam sagittis lectus et libero tincidunt, at laoreet risus dictum. Morbi id augue in lectus vulputate vulputate at id diam. Ut eget odio vehicula, aliquam ante eget, dictum neque. Nulla facilisi. Aenean eget erat sed est placerat sodales. Suspendisse potenti. Nam id risus ultricies, vulputate lectus nec, suscipit urna. Sed non velit vestibulum, consequat libero ut, consectetur justo.'),
    (15, 5, 'Proin vitae maximus purus. Sed ut turpis sit amet tortor congue placerat. Integer convallis magna nec ipsum consectetur facilisis. Duis mollis bibendum erat, vitae scelerisque ipsum feugiat vel. Vestibulum malesuada posuere sem, in egestas tortor laoreet nec. Nulla facilisi. Proin sodales justo a libero tincidunt, non eleifend magna dictum. Maecenas tincidunt nibh sit amet rhoncus tincidunt. Sed nec sem in ligula placerat consectetur id eu ligula. Aliquam erat volutpat. Etiam ac lacinia arcu, in tincidunt elit. Donec elementum magna a fermentum fringilla. Suspendisse lacinia purus a nibh luctus bibendum. Nullam vitae tristique metus. Donec tincidunt id ante sit amet tincidunt. Aliquam nec malesuada orci, vel ultrices magna. Donec ultricies, enim at scelerisque eleifend, elit enim luctus ligula, vitae laoreet lacus lorem eget odio.'),
    (16, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas non tellus id tortor eleifend dictum. Morbi id mollis justo, eu sodales ante. Sed ac aliquet enim. Donec tincidunt metus ac nisl vestibulum, vitae fringilla nulla congue. Curabitur viverra urna eu arcu auctor, sit amet lobortis sapien finibus. Suspendisse potenti. Praesent ullamcorper vulputate orci vitae scelerisque. Sed at nulla nec velit eleifend commodo. Nam dapibus velit a leo placerat, nec commodo mi tristique. Duis non odio nec libero eleifend sagittis. Nullam ut odio turpis. In a massa sed turpis auctor posuere. Sed sit amet odio nec ex sollicitudin tristique. Fusce aliquet venenatis justo, sit amet ultricies magna scelerisque eget.'),
    (16, 2, 'Suspendisse vitae quam varius, sollicitudin sapien in, gravida urna. Duis ultricies turpis justo, ac posuere libero facilisis eu. Aenean id metus vel neque convallis tincidunt a nec sapien. Integer hendrerit ultrices fermentum. Phasellus eget aliquam lorem, id dictum nulla. Donec tristique aliquet turpis a feugiat. Etiam id ipsum a augue tempor facilisis in sit amet nisi. Suspendisse potenti. Nullam commodo varius justo, eu lacinia lectus tempor at. Vestibulum euismod commodo lacus, a interdum lectus euismod at. Maecenas auctor euismod eros non vehicula. Nullam sed arcu quis libero maximus malesuada. Sed eu quam vitae lectus aliquam convallis. Aliquam consequat, nisi in laoreet commodo, quam leo facilisis libero, et placerat ante orci et mi.'),
    (18, 3, 'Vivamus placerat commodo eros, id congue neque dictum eget. Sed nec nunc libero. Nam nec odio nec nisl blandit lacinia a eget est. Nulla varius hendrerit metus, eget sodales nulla ullamcorper in. Nam feugiat tellus sed turpis tempor, in ultricies lacus facilisis. Curabitur vestibulum placerat nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed sit amet leo nec quam consequat faucibus eu nec est. Nulla facilisi. Cras nec convallis elit. Vivamus quis mi justo. Sed nec posuere urna, nec auctor purus. Curabitur finibus justo sit amet justo facilisis, id auctor urna efficitur.'),
    (19, 4, 'Pellentesque eget mauris quis augue feugiat tincidunt. Vivamus pharetra, metus sit amet gravida posuere, magna mi rhoncus ligula, vitae fermentum elit enim id sapien. Fusce tristique volutpat sapien, id laoreet ipsum consequat ut. Donec hendrerit, lacus in efficitur eleifend, turpis odio hendrerit neque, a eleifend elit urna nec velit. In hac habitasse platea dictumst. Aliquam sagittis lectus et libero tincidunt, at laoreet risus dictum. Morbi id augue in lectus vulputate vulputate at id diam. Ut eget odio vehicula, aliquam ante eget, dictum neque. Nulla facilisi. Aenean eget erat sed est placerat sodales. Suspendisse potenti. Nam id risus ultricies, vulputate lectus nec, suscipit urna. Sed non velit vestibulum, consequat libero ut, consectetur justo.'),
    (20, 5, 'Proin vitae maximus purus. Sed ut turpis sit amet tortor congue placerat. Integer convallis magna nec ipsum consectetur facilisis. Duis mollis bibendum erat, vitae scelerisque ipsum feugiat vel. Vestibulum malesuada posuere sem, in egestas tortor laoreet nec. Nulla facilisi. Proin sodales justo a libero tincidunt, non eleifend magna dictum. Maecenas tincidunt nibh sit amet rhoncus tincidunt. Sed nec sem in ligula placerat consectetur id eu ligula. Aliquam erat volutpat. Etiam ac lacinia arcu, in tincidunt elit. Donec elementum magna a fermentum fringilla. Suspendisse lacinia purus a nibh luctus bibendum. Nullam vitae tristique metus. Donec tincidunt id ante sit amet tincidunt. Aliquam nec malesuada orci, vel ultrices magna. Donec ultricies, enim at scelerisque eleifend, elit enim luctus ligula, vitae laoreet lacus lorem eget odio.');





